import {escapeHTML as esc, filterQueries, percent, chartPoints} from './model.mjs';

const paths={grid:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',activity:'M3 12h4l3-8 4 16 3-8h4',shield:'M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6z M8 12l3 3 5-6',list:'M8 5h13 M8 12h13 M8 19h13 M3 5h.01 M3 12h.01 M3 19h.01',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z',network:'M12 3v5 M5 16v-4h14v4 M9 3h6v5H9z M2 16h6v5H2z M16 16h6v5h-6z',clock:'M12 8v5l3 2 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',pause:'M8 5v14 M16 5v14',play:'m8 4 12 8-12 8z',arrow:'M5 12h14 M14 7l5 5-5 5',refresh:'M20 7v5h-5 M4 17v-5h5 M6 7a7 7 0 0 1 12-1l2 6 M18 17A7 7 0 0 1 6 18l-2-6',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14 M15 15l6 6',plus:'M12 5v14 M5 12h14',check:'m5 12 4 4L19 6',info:'M12 11v6 M12 7h.01 M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',lock:'M6 10h12v11H6z M8 10V6a4 4 0 0 1 8 0v4',logout:'M9 4H4v16h5 M10 12h11 M17 8l4 4-4 4',menu:'M4 6h16 M4 12h16 M4 18h16',trash:'M3 6h18 M9 6V3h6v3 M6 6l1 15h10l1-15 M10 10v7 M14 10v7'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.grid}"/></svg>`;
const fmt=n=>new Intl.NumberFormat().format(n||0);
const app=document.querySelector('#app');
let overview=null,settings=null,page='overview',querySearch='',queryStatus='',ruleTab='all',timer=null,polling=false,setupStep=1;
let setupData={name:'My network',token:'',password:'',source:'hagezi-light'};
const titles={overview:'Overview',queries:'Query log',rules:'Domain rules',lists:'Blocklists',settings:'Settings'};
const descriptions={overview:'A little less noise. A healthier network.',queries:'See what your devices are asking for, as it happens.',rules:'Fine-tune what belongs on your network.',lists:'Thoughtfully chosen protection. Kept up to date.',settings:'Make QuietDNS feel at home on your network.'};

async function api(path,method='GET',body){
 const response=await fetch('/api/'+path,{method,credentials:'same-origin',headers:body!==undefined?{'Content-Type':'application/json'}:{},body:body!==undefined?JSON.stringify(body):undefined});
 let data;try{data=await response.json()}catch{throw new Error('The server returned an unreadable response.')}
 if(!response.ok){if(response.status===401&&!['login','setup'].includes(path)){clearInterval(timer);login()}throw new Error(data.error||'The request failed.');}return data;
}
let toastTimeout;
function toast(message,error=false){const el=document.querySelector('#toast');el.textContent=message;el.className='visible'+(error?' error':'');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.className='',5000)}
async function busy(button,fn){if(button?.disabled)return;if(button)button.disabled=true;try{await fn()}catch(err){toast(err.message,true)}finally{if(button)button.disabled=false}}
function paused(){return overview&&new Date(overview.pausedUntil)>new Date()}
function relative(value){if(!value||new Date(value).getFullYear()<2000)return 'Not downloaded yet';const mins=Math.max(0,Math.floor((Date.now()-new Date(value))/60000));return mins<1?'Just now':mins<60?`${mins}m ago`:mins<1440?`${Math.floor(mins/60)}h ago`:new Date(value).toLocaleDateString()}
function empty(title,text,ico='activity'){return `<div class="empty">${icon(ico)}<strong>${esc(title)}</strong>${esc(text)}</div>`}
function footer(){return `<footer class="footer"><span>${icon('lock')} Query history stays on this device.</span><span>QuietDNS ${esc(overview?.version||'')} <span>·</span> Made for a quieter internet</span></footer>`}
function navigation(){return Object.entries(titles).map(([id,label])=>`<a href="#${id}" ${page===id?'aria-current="page"':''}>${icon({overview:'grid',queries:'activity',rules:'shield',lists:'list',settings:'settings'}[id])}${label}</a>`).join('')}
function shell(){
 app.innerHTML=`${overview.demo?'<div class="demo-banner">Design preview · illustrative data, not your Pi’s traffic</div>':''}<aside class="sidebar"><a class="brand" href="#overview"><img src="/mark.svg" alt="">QuietDNS</a><div class="workspace"><span class="network-icon">${icon('network')}</span><div><strong id="network-name">${esc(overview.name)}</strong><small>Local network</small></div></div><div class="nav-label">WORKSPACE</div><nav aria-label="Main navigation">${navigation()}</nav><div class="sidebar-bottom"><div class="protection-card" id="protection-card"></div><div class="version"><span>Self-hosted. Yours.</span><span>v${esc(overview.version)}</span></div></div></aside><div class="shell"><header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-menu" data-action="menu" aria-label="Toggle navigation">${icon('menu')}</button>Workspace <span>/</span> <strong id="breadcrumb">${titles[page]}</strong></div><div class="top-actions"><span class="local-badge"><span class="dot"></span> Local connection</span><button class="icon-button" data-action="logout" aria-label="Sign out" title="Sign out">${icon('logout')}</button><span class="avatar" aria-label="Administrator">AD</span></div></header><div id="connection"></div><main class="content" id="main"></main></div>`;
 renderPage();updateProtection();
}
function updateProtection(){const el=document.querySelector('#protection-card');if(!el)return;const isPaused=paused();el.innerHTML=`<strong><span class="dot ${isPaused?'amber':''}"></span>${isPaused?'Protection paused':'Protection is active'}</strong><p>${isPaused?'Resumes at '+new Date(overview.pausedUntil).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):fmt(overview.domains)+' domains on your blocklist.'}</p>`;document.querySelector('#network-name').textContent=overview.name;}
function heading(actions=''){return `<div class="page-heading"><div><h1>${titles[page]}</h1><p>${descriptions[page]}</p></div><div class="heading-actions">${actions}</div></div>`}
function stat(label,value,note,ico,unit=''){return `<div class="stat"><div class="stat-top">${label}${icon(ico)}</div><div class="stat-value">${value}${unit?`<em>${unit}</em>`:''}</div><div class="stat-note">${note}</div></div>`}
function chart(){
 const points=chartPoints(overview.buckets),max=Math.max(10,...points.map(p=>p.total));const x=i=>44+i*856/23,y=n=>157-n/max*130;
 const line=key=>points.map((p,i)=>`${i?'L':'M'}${x(i).toFixed(1)},${y(p[key]).toFixed(1)}`).join(' ');
 const axis=[0,.5,1].map(r=>`<line class="grid" x1="44" y1="${y(max*r)}" x2="900" y2="${y(max*r)}"/><text x="4" y="${y(max*r)+4}">${fmt(Math.round(max*r))}</text>`).join('');
 const labels=[0,6,12,18,23].map(i=>`<text x="${x(i)}" y="185" text-anchor="${i===0?'start':i===23?'end':'middle'}">${new Date(points[i].time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</text>`).join('');
 return `<div class="panel"><div class="panel-head"><div><h2>Network activity</h2><p>DNS queries across your network</p></div><div class="chart-legend"><span><i class="legend-line"></i> Total queries</span><span><i class="legend-line blocked"></i> Blocked</span></div></div><div class="chart-wrap"><svg class="chart" viewBox="0 0 920 196" preserveAspectRatio="none" role="img" aria-label="Hourly DNS query totals and blocked queries over the last 24 hours">${axis}<path class="area" d="${line('total')} L900,157 L44,157 Z"/><path class="line" d="${line('total')}"/><path class="blocked-line" d="${line('blocked')}"/>${labels}</svg>${overview.total===0?'<div class="chart-empty">Your network’s story starts with its first query.</div>':''}<div class="chart-bottom"><span>Hourly totals · local time</span><span>Last 24 hours</span></div></div></div>`
}
const statusLabel={allowed:'Allowed',blocked:'Blocked',error:'Error',notfound:'Not found'};
function tableRows(queries,full){return queries.map(q=>`<tr><td>${new Date(q.time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</td><td class="domain" title="${esc(q.domain)}">${esc(q.domain)}</td>${full?`<td>${esc(q.type)}</td>`:''}<td><span class="status ${esc(q.status)}" title="${esc(q.reason)}"><span class="dot"></span>${esc(statusLabel[q.status]||q.status)}</span></td>${full?`<td class="mono">${esc(q.client)}</td><td>${Number(q.latency).toFixed(1)} ms</td><td><button class="query-action" data-action="quick-rule" data-domain="${esc(q.domain)}" data-kind="${q.status==='blocked'?'allow':'block'}">${q.status==='blocked'?'Allow':'Block'}</button></td>`:`<td class="mono">${esc(q.client)}</td>`}</tr>`).join('')}
function queryTable(queries,full=false){return queries.length?`<div class="table-wrap"><table><thead><tr><th>TIME</th><th>DOMAIN</th>${full?'<th>TYPE</th>':''}<th>STATUS</th><th>CLIENT</th>${full?'<th>RESPONSE</th><th>ACTION</th>':''}</tr></thead><tbody>${tableRows(queries,full)}</tbody></table></div>`:empty('Nothing to show yet',overview.logging?'Queries appear when a device uses QuietDNS for DNS.':'Query logging is off. You can enable it in Settings.')}
function overviewPage(){
 const pauseButton=`<button class="button" data-action="pause">${icon(paused()?'play':'pause')}${paused()?'Resume protection':'Pause for 5 min'}</button>`;
 const statCards=stat('Total queries',fmt(overview.total),'In the last 24 hours','activity')+stat('Queries blocked',fmt(overview.blocked),`<span class="green">${percent(overview.blocked,overview.total)}% of all queries</span>`,'shield')+stat('Domains on blocklist',fmt(overview.domains),'Across your active lists and rules','list')+stat('Average response',Number(overview.latency).toFixed(1),'In the last 24 hours','clock','ms');
 const max=Math.max(1,...overview.topDomains.map(d=>d.count));
 const top=overview.topDomains.length?overview.topDomains.map(d=>`<div class="top-domain"><div class="top-domain-title"><span>${esc(d.domain)}</span><strong>${fmt(d.count)}</strong></div><svg viewBox="0 0 100 4" preserveAspectRatio="none" aria-hidden="true"><rect width="100" height="4" rx="2" fill="#f0f5f2"/><rect width="${d.count/max*100}" height="4" rx="2" fill="#aacaba"/></svg></div>`).join(''):empty('A quiet start','Blocked domains will appear here.','shield');
 return heading(`<span class="button">${icon('clock')} Last 24 hours</span>${pauseButton}`)+warnings()+`<div class="stats">${statCards}</div>${chart()}<div class="lower-grid"><section class="panel"><div class="panel-head"><div><h2>Recent queries</h2><p>A live look at your network</p></div><a class="text-button" href="#queries">View all →</a></div>${queryTable(overview.queries.slice(0,6))}<div class="panel-foot"><span>${overview.logging?'Updates every 5 seconds':'Query logging is off'}</span><span>${fmt(overview.clients)} clients in retained history</span></div></section><section class="panel"><div class="panel-head"><div><h2>Top blocked domains</h2><p>From retained query history</p></div>${icon('shield')}</div><div class="top-list">${top}</div><div class="tip">${icon('info')}<span>A blocked request is one less connection your device makes.</span></div></section></div>`+footer();
}
function warnings(){let html='';if(paused())html+='<div class="notice warning">Protection is temporarily paused. DNS forwarding continues; blocking will resume automatically.</div>';if(!overview.logging)html+='<div class="notice">Query logging is off. DNS protection still works; no query history or statistics are collected.</div>';if(overview.persistenceError)html+=`<div class="notice error">${esc(overview.persistenceError)}</div>`;if(overview.sources.some(s=>s.enabled&&(!s.count||s.error)))html+='<div class="notice warning">One or more blocklists need attention. <a class="text-button" href="#lists">Review blocklists →</a></div>';return html;}
function queriesPage(){return heading()+`<section class="panel"><div class="panel-head"><div><h2>Query activity</h2><p>Latest 2,000 queries · retained for up to 24 hours</p></div><span class="subtle">Live</span></div><div class="toolbar"><div class="search">${icon('search')}<input id="query-search" aria-label="Search domains or clients" placeholder="Search domains or clients…" value="${esc(querySearch)}"></div><select id="query-status" aria-label="Filter query status"><option value="">All statuses</option>${Object.entries(statusLabel).map(([id,label])=>`<option value="${id}" ${queryStatus===id?'selected':''}>${label}</option>`).join('')}</select></div><div id="query-results"></div></section>`+footer()}
function renderQueries(){const el=document.querySelector('#query-results');if(el){const list=filterQueries(overview.queries,querySearch,queryStatus);el.innerHTML=queryTable(list.slice(0,200),true)+`<div class="panel-foot"><span>${fmt(list.length)} matching queries · showing ${Math.min(list.length,200)}</span><span>Newest first</span></div>`}}
function rulesPage(){const rules=settings.rules.filter(r=>ruleTab==='all'||r.kind===ruleTab);return heading(`<button class="button primary" data-action="add-rule">${icon('plus')} Add domain rule</button>`)+`<div class="notice">Allow rules override blocklists and block rules. Every rule includes the domain’s subdomains.</div><div class="tabs" role="group" aria-label="Filter domain rules">${[['all','All rules'],['block','Blocked'],['allow','Allowed']].map(([id,label])=>`<button data-action="rule-tab" data-tab="${id}" class="${ruleTab===id?'active':''}" aria-pressed="${ruleTab===id}">${label}</button>`).join('')}</div><section class="panel"><div class="panel-head"><h2>Custom domain rules</h2><span class="subtle">${rules.length} rules</span></div>${rules.length?`<div class="table-wrap"><table><thead><tr><th>DOMAIN</th><th>ACTION</th><th>SCOPE</th><th></th></tr></thead><tbody>${rules.map(r=>`<tr><td class="domain">${esc(r.domain)}</td><td><span class="status ${r.kind==='allow'?'allowed':'blocked'}">${r.kind==='allow'?'Allow':'Block'}</span></td><td>Domain + subdomains</td><td><button class="icon-button" data-action="delete-rule" data-domain="${esc(r.domain)}" aria-label="Remove rule for ${esc(r.domain)}">${icon('trash')}</button></td></tr>`).join('')}</tbody></table></div>`:empty('Your rules, your call','Allow a domain that should work, or block one you would rather avoid.','shield')}</section>`+footer()}
function listsPage(){return heading(`<button class="button" data-action="refresh-lists" ${overview.updating?'disabled':''}>${icon('refresh')} ${overview.updating?'Updating…':'Update now'}</button>`)+`<div class="notice">Enabled lists refresh every 24 hours. If an update fails, QuietDNS keeps the last working copy.</div><section class="panel"><div class="panel-head"><div><h2>Recommended blocklists</h2><p>Maintained by HaGeZi · downloaded directly from GitHub</p></div></div>${overview.sources.map(s=>`<article class="list-card"><div class="list-symbol">${icon('shield')}</div><div class="list-details"><h3>${esc(s.name)} ${s.id==='hagezi-light'?'<span class="status allowed">Starter choice</span>':''}</h3><p>${esc(s.description)}</p><div class="list-meta"><span>${fmt(s.count)} domains cached</span><span>Updated ${relative(s.updated)}</span><a href="${esc(s.url)}" target="_blank" rel="noreferrer">View source ↗</a></div>${s.error?`<p class="form-error">Update failed: ${esc(s.error)}</p>`:''}</div><button class="toggle" role="switch" aria-label="Enable ${esc(s.name)}" aria-checked="${s.enabled}" data-action="toggle-source" data-id="${s.id}" data-enabled="${!s.enabled}"></button></article>`).join('')}</section><p class="health-note">Light and Normal overlap; enabling both is usually unnecessary. Domains are deduplicated automatically. DNS blocking cannot remove ads served from the same domains as the content you want.</p>`+footer()}
function settingsPage(){return heading()+`<div class="settings-grid"><section class="panel"><div class="panel-head"><h2>Network preferences</h2></div><form id="settings-form" class="form-body"><label>Network name<input name="name" value="${esc(settings.name)}" required maxlength="60"></label><label>Upstream DNS servers<input name="upstreams" value="${esc(settings.upstreams.join(', '))}" required spellcheck="false"></label><p class="field-help">One to three servers, separated by commas. Use IP:53, or [IPv6]:53. Queries use ordinary DNS and fall back to the next server on failure.</p><hr class="divider"><label class="check-label"><input type="checkbox" name="logging" ${settings.logging?'checked':''}> Keep query history and statistics</label><p class="field-help">Stores up to 2,000 recent queries and 24 hours of aggregate statistics on this device. Turning this off also clears existing history.</p><button class="button primary" type="submit">Save preferences</button><p id="settings-error" class="form-error" role="alert"></p></form><div class="panel-head"><div><h2>Connection check</h2><p>Test upstream connectivity and local blocking rules</p></div><button class="button" data-action="check">${icon('activity')} Run checks</button></div><div class="form-body"><div id="check-results"></div><p class="health-note">These checks run inside QuietDNS. Test from another device to confirm the published DNS port is reachable.</p><hr class="divider"><h3>Clear query history</h3><p class="health-note">Permanently removes stored queries and statistics. Domain rules are kept.</p><button class="button danger small" data-action="clear-history">Clear history</button></div></section><aside class="panel settings-aside"><h2>Connect a device</h2><p>Use this device’s reserved LAN address as your DNS server.</p><code>${esc(location.hostname)}</code><ol><li>Reserve the Pi’s address in your router’s DHCP settings.</li><li>Set one test device’s DNS server to this address.</li><li>Open a website, then check the query log.</li><li>When you’re ready, change your router’s DNS settings.</li></ol><hr class="divider"><p>Another DNS server, IPv6 DNS settings or browser secure DNS can bypass QuietDNS. IPv4 publishing is configured by the installer.</p><p>The dashboard uses local HTTP by default. Access it on a trusted LAN or through an SSH tunnel. Keep DNS and admin ports off the public internet.</p></aside></div>`+footer()}
function renderPage(){const main=document.querySelector('#main');if(!main||!overview)return;main.innerHTML=({overview:overviewPage,queries:queriesPage,rules:rulesPage,lists:listsPage,settings:settingsPage}[page]||overviewPage)();if(page==='queries')renderQueries()}
async function load(){const [o,s]=await Promise.all([api('overview'),api('settings')]);overview=o;settings=s}
async function refresh(render=true){await load();updateProtection();if(render)renderPage()}
async function start(){await load();page=titles[location.hash.slice(1)]?location.hash.slice(1):'overview';shell();clearInterval(timer);timer=setInterval(async()=>{if(polling||document.hidden||document.querySelector('dialog[open]'))return;polling=true;try{overview=await api('overview');updateProtection();document.querySelector('#connection')?.replaceChildren();if(['overview','lists'].includes(page)&&!document.activeElement.matches('input,select,button'))renderPage();if(page==='queries')renderQueries()}catch(err){const el=document.querySelector('#connection');if(el){el.innerHTML=`<div class="notice error connection-error">Connection interrupted. Showing the last received data. ${esc(err.message)}</div>`}}finally{polling=false}},5000)}
function authFrame(content){app.innerHTML=`<div class="auth"><aside class="auth-story"><div class="brand"><img src="/mark.svg" alt="">QuietDNS</div><div class="auth-message"><div class="eyebrow">LESS NOISE. MORE INTERNET.</div><h1>A quieter corner<br>of the internet.</h1><p>Give the devices you love a little breathing room. QuietDNS keeps unwanted connections out, right at home.</p><div class="auth-features"><span>${icon('shield')} Protection across your network</span><span>${icon('lock')} Your query history stays yours</span><span>${icon('network')} A small footprint on your Raspberry Pi</span></div></div><div class="auth-foot">Self-hosted · Open source · Thoughtfully simple</div></aside><main class="auth-main" id="main"><div class="auth-box">${content}</div></main></div>`}
function login(){clearInterval(timer);authFrame(`<h1>Welcome back.</h1><p>Your network is in good hands. Sign in to take a look.</p><form id="login-form"><label>Administrator password<input type="password" name="password" required autocomplete="current-password" maxlength="128"></label><p class="form-error" id="auth-error" role="alert"></p><button class="button primary" type="submit">Sign in ${icon('arrow')}</button></form><p class="health-note">Forgot your password? Use the password-reset instructions in the project README on your Pi.</p>`)}
function steps(){return `<div class="steps">${['Your space','Protection','Connect'].map((s,i)=>`${i?'<span class="step-line"></span>':''}<span class="step ${setupStep===i+1?'active':''}"><b>${i+1}</b>${s}</span>`).join('')}</div>`}
function setup(){
 if(setupStep===1){authFrame(steps()+`<h1>Make yourself at home.</h1><p>A name, a password, and you’re on your way to a quieter network.</p><form id="setup-account"><label>Network name<input name="name" value="${esc(setupData.name)}" maxlength="60" required autocomplete="off"></label><label>Installation key<input name="token" value="${esc(setupData.token)}" required autocomplete="off" spellcheck="false" placeholder="Printed by the installer"></label><label>Administrator password<input type="password" name="password" value="${esc(setupData.password)}" minlength="12" maxlength="128" required autocomplete="new-password" placeholder="At least 12 characters"></label><p class="form-error" id="auth-error" role="alert"></p><button type="submit" class="button primary">Choose your protection ${icon('arrow')}</button></form>`)}
 else if(setupStep===2){authFrame(steps()+`<h1>Start with a little quiet.</h1><p>Choose your starting blocklist. You can adjust it any time from the dashboard.</p><form id="setup-protection">${[['hagezi-light','HaGeZi Light','Recommended to start. Common ads and trackers, with fewer interruptions.'],['hagezi-normal','HaGeZi Normal','Broader protection. Some sites may need an allow rule.'],['none','Custom rules only','Start without a downloaded list and add your own domains.']].map(([id,name,desc])=>`<label class="source-choice"><input type="radio" name="source" value="${id}" ${setupData.source===id?'checked':''}><span><strong>${name}</strong><small>${desc}</small></span></label>`).join('')}<p class="health-note">Allowed queries are sent to Cloudflare, with Quad9 as fallback. You can change these servers in Settings.</p><p class="form-error" id="auth-error" role="alert"></p><div class="auth-actions"><button class="button" data-action="setup-back" type="button">Back</button><button class="button primary" type="submit">Create my network ${icon('arrow')}</button></div></form>`)}
 else {authFrame(steps()+`<div class="setup-success">${icon('check')}</div><h1>Your quiet starts here.</h1><p>Your administrator account is ready. The chosen list is downloading in the background; its status appears on the dashboard.</p><div class="dns-address"><small>YOUR DNS SERVER</small><strong>${esc(location.hostname)}</strong></div><p class="health-note">Set one test device’s DNS server to this address. Then open a website and watch the query log. Reserve the Pi’s address before changing DNS for your whole network.</p><div id="setup-checks" class="checks"></div><button class="button primary" data-action="finish-setup">Open my dashboard ${icon('arrow')}</button>`)}
}
function openRule(domain='',kind='block'){const form=document.querySelector('#rule-form');form.elements.domain.value=domain;form.elements.kind.value=kind;document.querySelector('#rule-error').textContent='';document.querySelector('#rule-dialog').showModal();form.elements.domain.focus()}
document.addEventListener('click',async event=>{
 const button=event.target.closest('[data-action]');if(!button)return;const action=button.dataset.action;
 if(action==='menu'){document.querySelector('.sidebar').classList.toggle('open');return}
 if(action==='close-dialog'){document.querySelector('#rule-dialog').close();return}
 if(action==='add-rule'||action==='quick-rule'){openRule(button.dataset.domain,button.dataset.kind);return}
 if(action==='rule-tab'){ruleTab=button.dataset.tab;renderPage();return}
 if(action==='setup-back'){setupStep=1;setup();return}
 await busy(button,async()=>{
  if(action==='logout'){await api('logout','POST',{});login();return}
  if(action==='finish-setup'){setupData={};location.hash='overview';await start();return}
  if(action==='pause'){await api('pause','POST',{minutes:paused()?0:5});await refresh();toast(paused()?'Protection paused for 5 minutes.':'Protection resumed.');return}
  if(action==='delete-rule'){await api('rules','DELETE',{domain:button.dataset.domain});await refresh();toast('Domain rule removed.');return}
  if(action==='toggle-source'){await api('sources','POST',{id:button.dataset.id,enabled:button.dataset.enabled==='true'});await refresh();toast('Blocklist preference saved.');return}
  if(action==='refresh-lists'){await api('refresh','POST',{});overview.updating=true;renderPage();toast('Updating your enabled blocklists…');return}
  if(action==='check'){const results=await api('check','POST',{});document.querySelector('#check-results').innerHTML=results.map(r=>`<div class="check-result ${r.ok?'':'failed'}"><span>${esc(r.name)}</span><strong>${r.ok?'Passed':'Needs attention'}</strong></div>`).join('');return}
  if(action==='clear-history'){if(!confirm('Permanently clear all query history and statistics?'))return;await api('history','DELETE',{});await refresh();toast('Query history cleared.');return}
 });
});
document.addEventListener('submit',async event=>{
 const form=event.target;event.preventDefault();const values=Object.fromEntries(new FormData(form));const button=form.querySelector('button[type=submit]');
 if(form.id==='setup-account'){setupData={...setupData,...values};setupStep=2;setup();return}
 await busy(button,async()=>{
  try{
   if(form.id==='login-form'){await api('login','POST',values);await start()}
   else if(form.id==='setup-protection'){setupData.source=values.source;await api('setup','POST',setupData);setupData.password='';setupData.token='';setupStep=3;setup()}
   else if(form.id==='rule-form'){await api('rules','POST',values);document.querySelector('#rule-dialog').close();await refresh();toast('Domain rule saved. It is active immediately.')}
   else if(form.id==='settings-form'){await api('settings','PUT',{name:values.name,upstreams:values.upstreams.split(',').map(s=>s.trim()).filter(Boolean),logging:form.elements.logging.checked});await refresh();toast('Preferences saved.')}
  }catch(err){const target=form.querySelector('.form-error');if(target)target.textContent=err.message;else throw err}
 });
});
document.addEventListener('input',event=>{if(event.target.id==='query-search'){querySearch=event.target.value;renderQueries()}});
document.addEventListener('change',event=>{if(event.target.id==='query-status'){queryStatus=event.target.value;renderQueries()}});
window.addEventListener('hashchange',()=>{if(!document.querySelector('.shell'))return;page=titles[location.hash.slice(1)]?location.hash.slice(1):'overview';document.querySelector('nav').innerHTML=navigation();document.querySelector('#breadcrumb').textContent=titles[page];document.querySelector('.sidebar').classList.remove('open');renderPage()});
async function boot(){try{const status=await api('status');if(status.setupRequired)setup();else if(!status.authenticated)login();else await start()}catch(err){authFrame(`<h1>Let’s reconnect.</h1><p>${esc(err.message)}</p><button class="button primary" id="retry">Try again</button>`);document.querySelector('#retry').addEventListener('click',boot)}}
boot();
